#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Ilib -Iinclude
CFLAGS = -pedantic -std=c++11 -Wall -fexceptions
RESINC = 
LIBDIR = -Lspirit -Linclude
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -Iinclude/abstract -Iinclude/parser -Iinclude -Iinclude/fsml -Iinclude/validator -Iinclude/generate
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/fsmlpp

INC_RELEASE = $(INC) -Iinclude/abstract -Iinclude/parser -Iinclude -Iinclude/fsml -Iinclude/validator -Iinclude/generate
CFLAGS_RELEASE = $(CFLAGS) -fexpensive-optimizations -O3
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/fsmlpp

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/src/validator/Validator.o $(OBJDIR_DEBUG)/src/validator/Exception.o $(OBJDIR_DEBUG)/src/parser/Step.o $(OBJDIR_DEBUG)/src/parser/State.o $(OBJDIR_DEBUG)/src/parser/Parser.o $(OBJDIR_DEBUG)/src/parser/Machine.o $(OBJDIR_DEBUG)/src/generate/Generator.o $(OBJDIR_DEBUG)/src/generate/Generate.o $(OBJDIR_DEBUG)/src/fsml/Step.o $(OBJDIR_DEBUG)/src/fsml/State.o $(OBJDIR_DEBUG)/src/fsml/Machine.o $(OBJDIR_DEBUG)/src/fsml/Action.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/src/validator/Validator.o $(OBJDIR_RELEASE)/src/validator/Exception.o $(OBJDIR_RELEASE)/src/parser/Step.o $(OBJDIR_RELEASE)/src/parser/State.o $(OBJDIR_RELEASE)/src/parser/Parser.o $(OBJDIR_RELEASE)/src/parser/Machine.o $(OBJDIR_RELEASE)/src/generate/Generator.o $(OBJDIR_RELEASE)/src/generate/Generate.o $(OBJDIR_RELEASE)/src/fsml/Step.o $(OBJDIR_RELEASE)/src/fsml/State.o $(OBJDIR_RELEASE)/src/fsml/Machine.o $(OBJDIR_RELEASE)/src/fsml/Action.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/src/validator || mkdir -p $(OBJDIR_DEBUG)/src/validator
	test -d $(OBJDIR_DEBUG)/src/parser || mkdir -p $(OBJDIR_DEBUG)/src/parser
	test -d $(OBJDIR_DEBUG)/src/generate || mkdir -p $(OBJDIR_DEBUG)/src/generate
	test -d $(OBJDIR_DEBUG)/src/fsml || mkdir -p $(OBJDIR_DEBUG)/src/fsml

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/src/validator/Validator.o: src/validator/Validator.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/validator/Validator.cpp -o $(OBJDIR_DEBUG)/src/validator/Validator.o

$(OBJDIR_DEBUG)/src/validator/Exception.o: src/validator/Exception.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/validator/Exception.cpp -o $(OBJDIR_DEBUG)/src/validator/Exception.o

$(OBJDIR_DEBUG)/src/parser/Step.o: src/parser/Step.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/parser/Step.cpp -o $(OBJDIR_DEBUG)/src/parser/Step.o

$(OBJDIR_DEBUG)/src/parser/State.o: src/parser/State.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/parser/State.cpp -o $(OBJDIR_DEBUG)/src/parser/State.o

$(OBJDIR_DEBUG)/src/parser/Parser.o: src/parser/Parser.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/parser/Parser.cpp -o $(OBJDIR_DEBUG)/src/parser/Parser.o

$(OBJDIR_DEBUG)/src/parser/Machine.o: src/parser/Machine.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/parser/Machine.cpp -o $(OBJDIR_DEBUG)/src/parser/Machine.o

$(OBJDIR_DEBUG)/src/generate/Generator.o: src/generate/Generator.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/generate/Generator.cpp -o $(OBJDIR_DEBUG)/src/generate/Generator.o

$(OBJDIR_DEBUG)/src/generate/Generate.o: src/generate/Generate.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/generate/Generate.cpp -o $(OBJDIR_DEBUG)/src/generate/Generate.o

$(OBJDIR_DEBUG)/src/fsml/Step.o: src/fsml/Step.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/Step.cpp -o $(OBJDIR_DEBUG)/src/fsml/Step.o

$(OBJDIR_DEBUG)/src/fsml/State.o: src/fsml/State.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/State.cpp -o $(OBJDIR_DEBUG)/src/fsml/State.o

$(OBJDIR_DEBUG)/src/fsml/Machine.o: src/fsml/Machine.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/Machine.cpp -o $(OBJDIR_DEBUG)/src/fsml/Machine.o

$(OBJDIR_DEBUG)/src/fsml/Action.o: src/fsml/Action.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/Action.cpp -o $(OBJDIR_DEBUG)/src/fsml/Action.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/src/validator
	rm -rf $(OBJDIR_DEBUG)/src/parser
	rm -rf $(OBJDIR_DEBUG)/src/generate
	rm -rf $(OBJDIR_DEBUG)/src/fsml

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/src/validator || mkdir -p $(OBJDIR_RELEASE)/src/validator
	test -d $(OBJDIR_RELEASE)/src/parser || mkdir -p $(OBJDIR_RELEASE)/src/parser
	test -d $(OBJDIR_RELEASE)/src/generate || mkdir -p $(OBJDIR_RELEASE)/src/generate
	test -d $(OBJDIR_RELEASE)/src/fsml || mkdir -p $(OBJDIR_RELEASE)/src/fsml

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/src/validator/Validator.o: src/validator/Validator.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/validator/Validator.cpp -o $(OBJDIR_RELEASE)/src/validator/Validator.o

$(OBJDIR_RELEASE)/src/validator/Exception.o: src/validator/Exception.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/validator/Exception.cpp -o $(OBJDIR_RELEASE)/src/validator/Exception.o

$(OBJDIR_RELEASE)/src/parser/Step.o: src/parser/Step.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/parser/Step.cpp -o $(OBJDIR_RELEASE)/src/parser/Step.o

$(OBJDIR_RELEASE)/src/parser/State.o: src/parser/State.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/parser/State.cpp -o $(OBJDIR_RELEASE)/src/parser/State.o

$(OBJDIR_RELEASE)/src/parser/Parser.o: src/parser/Parser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/parser/Parser.cpp -o $(OBJDIR_RELEASE)/src/parser/Parser.o

$(OBJDIR_RELEASE)/src/parser/Machine.o: src/parser/Machine.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/parser/Machine.cpp -o $(OBJDIR_RELEASE)/src/parser/Machine.o

$(OBJDIR_RELEASE)/src/generate/Generator.o: src/generate/Generator.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/generate/Generator.cpp -o $(OBJDIR_RELEASE)/src/generate/Generator.o

$(OBJDIR_RELEASE)/src/generate/Generate.o: src/generate/Generate.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/generate/Generate.cpp -o $(OBJDIR_RELEASE)/src/generate/Generate.o

$(OBJDIR_RELEASE)/src/fsml/Step.o: src/fsml/Step.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/Step.cpp -o $(OBJDIR_RELEASE)/src/fsml/Step.o

$(OBJDIR_RELEASE)/src/fsml/State.o: src/fsml/State.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/State.cpp -o $(OBJDIR_RELEASE)/src/fsml/State.o

$(OBJDIR_RELEASE)/src/fsml/Machine.o: src/fsml/Machine.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/Machine.cpp -o $(OBJDIR_RELEASE)/src/fsml/Machine.o

$(OBJDIR_RELEASE)/src/fsml/Action.o: src/fsml/Action.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/Action.cpp -o $(OBJDIR_RELEASE)/src/fsml/Action.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src/validator
	rm -rf $(OBJDIR_RELEASE)/src/parser
	rm -rf $(OBJDIR_RELEASE)/src/generate
	rm -rf $(OBJDIR_RELEASE)/src/fsml

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

