#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Iinclude -Ilib
CFLAGS = -pedantic -std=c++11 -Wextra -Wall -fexceptions
RESINC = 
LIBDIR = -Lspirit -Linclude
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -Iinclude -Iinclude/fsml
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/fsmlpp

INC_RELEASE = $(INC) -Iinclude -Iinclude/fsml
CFLAGS_RELEASE = $(CFLAGS) -fexpensive-optimizations -O3
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/fsmlpp

INC_SIMULATION = $(INC) -Iinclude -Iinclude/fsml
CFLAGS_SIMULATION = $(CFLAGS) -g
RESINC_SIMULATION = $(RESINC)
RCFLAGS_SIMULATION = $(RCFLAGS)
LIBDIR_SIMULATION = $(LIBDIR)
LIB_SIMULATION = $(LIB)
LDFLAGS_SIMULATION = $(LDFLAGS)
OBJDIR_SIMULATION = obj/Debug
DEP_SIMULATION = 
OUT_SIMULATION = bin/Simulation/fsmlsim

INC_TEST = $(INC) -Iinclude -Iinclude/fsml
CFLAGS_TEST = $(CFLAGS) -g
RESINC_TEST = $(RESINC)
RCFLAGS_TEST = $(RCFLAGS)
LIBDIR_TEST = $(LIBDIR)
LIB_TEST = $(LIB)
LDFLAGS_TEST = $(LDFLAGS) -lgtest -lpthread
OBJDIR_TEST = obj/Debug
DEP_TEST = 
OUT_TEST = bin/Test/fsmlpptest

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/fsml/Action.o $(OBJDIR_DEBUG)/src/main.o $(OBJDIR_DEBUG)/src/fsml/Step.o $(OBJDIR_DEBUG)/src/fsml/State.o $(OBJDIR_DEBUG)/src/fsml/Machine.o $(OBJDIR_DEBUG)/src/fsml/InputOutput.o $(OBJDIR_DEBUG)/src/fsml/Generator.o $(OBJDIR_DEBUG)/src/fsml/FlatStep.o $(OBJDIR_DEBUG)/src/fsml/FlatMachine.o $(OBJDIR_DEBUG)/src/fsml/Exceptions.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/fsml/Action.o $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/fsml/Step.o $(OBJDIR_RELEASE)/src/fsml/State.o $(OBJDIR_RELEASE)/src/fsml/Machine.o $(OBJDIR_RELEASE)/src/fsml/InputOutput.o $(OBJDIR_RELEASE)/src/fsml/Generator.o $(OBJDIR_RELEASE)/src/fsml/FlatStep.o $(OBJDIR_RELEASE)/src/fsml/FlatMachine.o $(OBJDIR_RELEASE)/src/fsml/Exceptions.o

OBJ_SIMULATION = $(OBJDIR_SIMULATION)/src/fsml/Action.o $(OBJDIR_SIMULATION)/src/simulate.o $(OBJDIR_SIMULATION)/src/fsml/Step.o $(OBJDIR_SIMULATION)/src/fsml/State.o $(OBJDIR_SIMULATION)/src/fsml/Machine.o $(OBJDIR_SIMULATION)/src/fsml/InputOutput.o $(OBJDIR_SIMULATION)/src/fsml/Generator.o $(OBJDIR_SIMULATION)/src/fsml/FlatStep.o $(OBJDIR_SIMULATION)/src/fsml/FlatMachine.o $(OBJDIR_SIMULATION)/src/fsml/Exceptions.o

OBJ_TEST = $(OBJDIR_TEST)/src/fsml/Action.o $(OBJDIR_TEST)/src/test.o $(OBJDIR_TEST)/src/fsml/Step.o $(OBJDIR_TEST)/src/fsml/State.o $(OBJDIR_TEST)/src/fsml/Machine.o $(OBJDIR_TEST)/src/fsml/InputOutput.o $(OBJDIR_TEST)/src/fsml/Generator.o $(OBJDIR_TEST)/src/fsml/FlatStep.o $(OBJDIR_TEST)/src/fsml/FlatMachine.o $(OBJDIR_TEST)/src/fsml/Exceptions.o

all: debug release simulation test

clean: clean_debug clean_release clean_simulation clean_test

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src/fsml || mkdir -p $(OBJDIR_DEBUG)/src/fsml
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/fsml/Action.o: src/fsml/Action.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/Action.cpp -o $(OBJDIR_DEBUG)/src/fsml/Action.o

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

$(OBJDIR_DEBUG)/src/fsml/Step.o: src/fsml/Step.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/Step.cpp -o $(OBJDIR_DEBUG)/src/fsml/Step.o

$(OBJDIR_DEBUG)/src/fsml/State.o: src/fsml/State.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/State.cpp -o $(OBJDIR_DEBUG)/src/fsml/State.o

$(OBJDIR_DEBUG)/src/fsml/Machine.o: src/fsml/Machine.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/Machine.cpp -o $(OBJDIR_DEBUG)/src/fsml/Machine.o

$(OBJDIR_DEBUG)/src/fsml/InputOutput.o: src/fsml/InputOutput.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/InputOutput.cpp -o $(OBJDIR_DEBUG)/src/fsml/InputOutput.o

$(OBJDIR_DEBUG)/src/fsml/Generator.o: src/fsml/Generator.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/Generator.cpp -o $(OBJDIR_DEBUG)/src/fsml/Generator.o

$(OBJDIR_DEBUG)/src/fsml/FlatStep.o: src/fsml/FlatStep.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/FlatStep.cpp -o $(OBJDIR_DEBUG)/src/fsml/FlatStep.o

$(OBJDIR_DEBUG)/src/fsml/FlatMachine.o: src/fsml/FlatMachine.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/FlatMachine.cpp -o $(OBJDIR_DEBUG)/src/fsml/FlatMachine.o

$(OBJDIR_DEBUG)/src/fsml/Exceptions.o: src/fsml/Exceptions.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/fsml/Exceptions.cpp -o $(OBJDIR_DEBUG)/src/fsml/Exceptions.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src/fsml
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src/fsml || mkdir -p $(OBJDIR_RELEASE)/src/fsml
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/fsml/Action.o: src/fsml/Action.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/Action.cpp -o $(OBJDIR_RELEASE)/src/fsml/Action.o

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/fsml/Step.o: src/fsml/Step.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/Step.cpp -o $(OBJDIR_RELEASE)/src/fsml/Step.o

$(OBJDIR_RELEASE)/src/fsml/State.o: src/fsml/State.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/State.cpp -o $(OBJDIR_RELEASE)/src/fsml/State.o

$(OBJDIR_RELEASE)/src/fsml/Machine.o: src/fsml/Machine.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/Machine.cpp -o $(OBJDIR_RELEASE)/src/fsml/Machine.o

$(OBJDIR_RELEASE)/src/fsml/InputOutput.o: src/fsml/InputOutput.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/InputOutput.cpp -o $(OBJDIR_RELEASE)/src/fsml/InputOutput.o

$(OBJDIR_RELEASE)/src/fsml/Generator.o: src/fsml/Generator.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/Generator.cpp -o $(OBJDIR_RELEASE)/src/fsml/Generator.o

$(OBJDIR_RELEASE)/src/fsml/FlatStep.o: src/fsml/FlatStep.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/FlatStep.cpp -o $(OBJDIR_RELEASE)/src/fsml/FlatStep.o

$(OBJDIR_RELEASE)/src/fsml/FlatMachine.o: src/fsml/FlatMachine.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/FlatMachine.cpp -o $(OBJDIR_RELEASE)/src/fsml/FlatMachine.o

$(OBJDIR_RELEASE)/src/fsml/Exceptions.o: src/fsml/Exceptions.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/fsml/Exceptions.cpp -o $(OBJDIR_RELEASE)/src/fsml/Exceptions.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src/fsml
	rm -rf $(OBJDIR_RELEASE)/src

before_simulation: 
	test -d bin/Simulation || mkdir -p bin/Simulation
	test -d $(OBJDIR_SIMULATION)/src/fsml || mkdir -p $(OBJDIR_SIMULATION)/src/fsml
	test -d $(OBJDIR_SIMULATION)/src || mkdir -p $(OBJDIR_SIMULATION)/src

after_simulation: 

simulation: before_simulation out_simulation after_simulation

out_simulation: before_simulation $(OBJ_SIMULATION) $(DEP_SIMULATION)
	$(LD) $(LIBDIR_SIMULATION) -o $(OUT_SIMULATION) $(OBJ_SIMULATION)  $(LDFLAGS_SIMULATION) $(LIB_SIMULATION)

$(OBJDIR_SIMULATION)/src/fsml/Action.o: src/fsml/Action.cpp
	$(CXX) $(CFLAGS_SIMULATION) $(INC_SIMULATION) -c src/fsml/Action.cpp -o $(OBJDIR_SIMULATION)/src/fsml/Action.o

$(OBJDIR_SIMULATION)/src/simulate.o: src/simulate.cpp
	$(CXX) $(CFLAGS_SIMULATION) $(INC_SIMULATION) -c src/simulate.cpp -o $(OBJDIR_SIMULATION)/src/simulate.o

$(OBJDIR_SIMULATION)/src/fsml/Step.o: src/fsml/Step.cpp
	$(CXX) $(CFLAGS_SIMULATION) $(INC_SIMULATION) -c src/fsml/Step.cpp -o $(OBJDIR_SIMULATION)/src/fsml/Step.o

$(OBJDIR_SIMULATION)/src/fsml/State.o: src/fsml/State.cpp
	$(CXX) $(CFLAGS_SIMULATION) $(INC_SIMULATION) -c src/fsml/State.cpp -o $(OBJDIR_SIMULATION)/src/fsml/State.o

$(OBJDIR_SIMULATION)/src/fsml/Machine.o: src/fsml/Machine.cpp
	$(CXX) $(CFLAGS_SIMULATION) $(INC_SIMULATION) -c src/fsml/Machine.cpp -o $(OBJDIR_SIMULATION)/src/fsml/Machine.o

$(OBJDIR_SIMULATION)/src/fsml/InputOutput.o: src/fsml/InputOutput.cpp
	$(CXX) $(CFLAGS_SIMULATION) $(INC_SIMULATION) -c src/fsml/InputOutput.cpp -o $(OBJDIR_SIMULATION)/src/fsml/InputOutput.o

$(OBJDIR_SIMULATION)/src/fsml/Generator.o: src/fsml/Generator.cpp
	$(CXX) $(CFLAGS_SIMULATION) $(INC_SIMULATION) -c src/fsml/Generator.cpp -o $(OBJDIR_SIMULATION)/src/fsml/Generator.o

$(OBJDIR_SIMULATION)/src/fsml/FlatStep.o: src/fsml/FlatStep.cpp
	$(CXX) $(CFLAGS_SIMULATION) $(INC_SIMULATION) -c src/fsml/FlatStep.cpp -o $(OBJDIR_SIMULATION)/src/fsml/FlatStep.o

$(OBJDIR_SIMULATION)/src/fsml/FlatMachine.o: src/fsml/FlatMachine.cpp
	$(CXX) $(CFLAGS_SIMULATION) $(INC_SIMULATION) -c src/fsml/FlatMachine.cpp -o $(OBJDIR_SIMULATION)/src/fsml/FlatMachine.o

$(OBJDIR_SIMULATION)/src/fsml/Exceptions.o: src/fsml/Exceptions.cpp
	$(CXX) $(CFLAGS_SIMULATION) $(INC_SIMULATION) -c src/fsml/Exceptions.cpp -o $(OBJDIR_SIMULATION)/src/fsml/Exceptions.o

clean_simulation: 
	rm -f $(OBJ_SIMULATION) $(OUT_SIMULATION)
	rm -rf bin/Simulation
	rm -rf $(OBJDIR_SIMULATION)/src/fsml
	rm -rf $(OBJDIR_SIMULATION)/src

before_test: 
	test -d bin/Test || mkdir -p bin/Test
	test -d $(OBJDIR_TEST)/src/fsml || mkdir -p $(OBJDIR_TEST)/src/fsml
	test -d $(OBJDIR_TEST)/src || mkdir -p $(OBJDIR_TEST)/src

after_test: 

test: before_test out_test after_test

out_test: before_test $(OBJ_TEST) $(DEP_TEST)
	$(LD) $(LIBDIR_TEST) -o $(OUT_TEST) $(OBJ_TEST)  $(LDFLAGS_TEST) $(LIB_TEST)

$(OBJDIR_TEST)/src/fsml/Action.o: src/fsml/Action.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/fsml/Action.cpp -o $(OBJDIR_TEST)/src/fsml/Action.o

$(OBJDIR_TEST)/src/test.o: src/test.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/test.cpp -o $(OBJDIR_TEST)/src/test.o

$(OBJDIR_TEST)/src/fsml/Step.o: src/fsml/Step.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/fsml/Step.cpp -o $(OBJDIR_TEST)/src/fsml/Step.o

$(OBJDIR_TEST)/src/fsml/State.o: src/fsml/State.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/fsml/State.cpp -o $(OBJDIR_TEST)/src/fsml/State.o

$(OBJDIR_TEST)/src/fsml/Machine.o: src/fsml/Machine.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/fsml/Machine.cpp -o $(OBJDIR_TEST)/src/fsml/Machine.o

$(OBJDIR_TEST)/src/fsml/InputOutput.o: src/fsml/InputOutput.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/fsml/InputOutput.cpp -o $(OBJDIR_TEST)/src/fsml/InputOutput.o

$(OBJDIR_TEST)/src/fsml/Generator.o: src/fsml/Generator.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/fsml/Generator.cpp -o $(OBJDIR_TEST)/src/fsml/Generator.o

$(OBJDIR_TEST)/src/fsml/FlatStep.o: src/fsml/FlatStep.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/fsml/FlatStep.cpp -o $(OBJDIR_TEST)/src/fsml/FlatStep.o

$(OBJDIR_TEST)/src/fsml/FlatMachine.o: src/fsml/FlatMachine.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/fsml/FlatMachine.cpp -o $(OBJDIR_TEST)/src/fsml/FlatMachine.o

$(OBJDIR_TEST)/src/fsml/Exceptions.o: src/fsml/Exceptions.cpp
	$(CXX) $(CFLAGS_TEST) $(INC_TEST) -c src/fsml/Exceptions.cpp -o $(OBJDIR_TEST)/src/fsml/Exceptions.o

clean_test: 
	rm -f $(OBJ_TEST) $(OUT_TEST)
	rm -rf bin/Test
	rm -rf $(OBJDIR_TEST)/src/fsml
	rm -rf $(OBJDIR_TEST)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release before_simulation after_simulation clean_simulation before_test after_test clean_test

