#ifndef FSML_SAMPLEFSML_HPP
#define FSML_SAMPLEFSML_HPP
#include "fsml/Machine.hpp"
namespace fsml
{
/// @file Generated by FSML++.

/**This generated code will create a final state machine as per the following FSML code:

initial state locked {
  pass/alarm -> exception;
  ticket/collect -> unlocked;
}
state exception {
  mute;
  pass;
  release -> locked;
  ticket/eject;
}
state unlocked {
  pass -> locked;
  ticket/eject;
}

@return An fsml::Machine corresponding to the FSML code it was generated from.*/
Machine createSampleFsml()
{
    return Machine{
		// Initial States
		{
			"locked",
		},
		// Other States
		{
			"exception",
			"unlocked",
		},
		// Transitions
		{
			{"exception", "mute", "", "exception"},
			{"exception", "pass", "", "exception"},
			{"exception", "release", "", "locked"},
			{"exception", "ticket", "eject", "exception"},
			{"unlocked", "pass", "", "locked"},
			{"locked", "pass", "alarm", "exception"},
			{"locked", "ticket", "collect", "unlocked"},
			{"unlocked", "ticket", "eject", "unlocked"},
		}
	};
}

}
#endif // FSML_SAMPLEFSML_HPP
