#ifndef FSML_STRUCTOLD_HPP
#define FSML_STRUCTOLD_HPP
#include "fsml/Machine.hpp"
namespace fsml
{
/// @file Generated by FSML++.

/**This generated code will create a final state machine as per the following FSML code:

initial state FsmlCode {
  parse -> AstMachine;
}
state AstMachine {
  flatten -> FlatMachine;
}
state FlatMachine {
  construct/validate -> Machine;
  generateCode -> HPP;
}
state Machine {
}
state HPP {
  construct/validate -> Machine;
}

@return An fsml::Machine corresponding to the FSML code it was generated from.*/
Machine createStructOld()
{
    return Machine{
		// Initial States
		std::vector<std::string>{
		"FsmlCode",
		},
		// Other States
		std::vector<std::string>{
		"AstMachine",
		"FlatMachine",
		"Machine",
		"HPP",
		},
		// Transitions
		std::vector<FlatStep>{
		{"FsmlCode", "parse", "", "AstMachine"},
		{"AstMachine", "flatten", "", "FlatMachine"},
		{"FlatMachine", "construct", "validate", "Machine"},
		{"FlatMachine", "generateCode", "", "HPP"},
		{"HPP", "construct", "validate", "Machine"},
		}
	};
}

}
#endif // FSML_STRUCTOLD_HPP
